uploads = []
generated = []

[[outputs]]
id = "H0MG-tKlke2RZn5usvYGR"
uri = "file://nonfiction-ai-studio-documentation.docx"
type = "word_document"
title = "Nonfiction AI Studio — User Documentation"
logical_id = "aa252840-2c83-42d2-bd5d-c25ea33ef6dd"
