import { useEffect, useState, useRef } from "react";
import { extractAsinFromAmazonUrl } from "@/lib/analysis/asin";

function newBookId() {
  if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
  return `bk-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function IntelChip({ label, value }) {
  if (!value) return null;
  return (
    <div className="rounded-xl border border-slate-200 bg-white px-4 py-3">
      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p>
      <p className="mt-1 text-sm text-slate-800 leading-snug">{value}</p>
    </div>
  );
}

function IntelTags({ label, values, colorClass = "bg-sky-100 text-sky-800" }) {
  if (!Array.isArray(values) || !values.length) return null;
  return (
    <div>
      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1.5">{label}</p>
      <div className="flex flex-wrap gap-1.5">
        {values.map((v, i) => (
          <span key={`${i}-${v}`} className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${colorClass}`}>{v}</span>
        ))}
      </div>
    </div>
  );
}

function KeywordChip({ keyword, onRemove }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs font-medium text-sky-800">
      {keyword}
      <button
        type="button"
        onClick={() => onRemove(keyword)}
        className="flex h-3.5 w-3.5 shrink-0 items-center justify-center rounded-full text-sky-500 hover:bg-sky-200 hover:text-sky-900 transition-colors"
        aria-label={`Remove ${keyword}`}
      >
        ×
      </button>
    </span>
  );
}

export default function AnalysisStep({ research, analysis, errors, updateAnalysis, patchBook, removeBook, updateResearch }) {
  const [loadingSearch, setLoadingSearch]         = useState(false);
  const [loadingKeywords, setLoadingKeywords]     = useState(false);
  const [loadingProductId, setLoadingProductId]   = useState(null);
  const [localMsg, setLocalMsg]                   = useState("");
  const [manualUrl, setManualUrl]                 = useState("");
  const [manualTitle, setManualTitle]             = useState("");
  const [expandedId, setExpandedId]               = useState(null);
  const [intelLoading, setIntelLoading]           = useState(false);
  const [intelError, setIntelError]               = useState("");
  const [showBooks, setShowBooks]                 = useState(true);
  const [sortBy, setSortBy]                       = useState("default");
  const [newKeyword, setNewKeyword]               = useState("");
  const [searchProgress, setSearchProgress]       = useState("");
  const keywordInputRef = useRef(null);

  const amazonDomain = analysis.amazonDomain || "amazon.com";
  const intelligence = analysis.intelligence  || null;
  const isNewIntel   = intelligence && typeof intelligence.targetAudience === "object" && !Array.isArray(intelligence.targetAudience);

  // Keywords stored in analysis state for persistence
  const keywords = Array.isArray(analysis.keywords) ? analysis.keywords : [];

  function setKeywords(kws) {
    updateAnalysis((prev) => ({ ...prev, keywords: kws }));
  }

  // ── Auto-generate keywords on first mount if none exist ──────────────────
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (keywords.length > 0) { hasAutoGenerated.current = true; return; }
    const hasContext = research.mainNicheLabel || research.subNicheLabel || research.deepNicheLabel
      || research.bookTitle || research.bookTopic || research.genre;
    if (!hasContext) return;
    hasAutoGenerated.current = true;
    generateKeywords();
  }, [
    research.mainNicheLabel, research.subNicheLabel, research.deepNicheLabel,
    research.bookTitle, research.bookTopic, research.genre
  ]);

  async function generateKeywords() {
    setLoadingKeywords(true);
    setLocalMsg("");
    try {
      const res = await fetch("/api/analysis/generate-keywords", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          niche:     research.mainNicheLabel || research.genre || "",
          subNiche:  research.subNicheLabel  || "",
          deepNiche: research.deepNicheLabel || "",
          title:     research.bookTitle      || "",
          subtitle:  research.bookSubtitle   || "",
          bookTopic: research.bookTopic      || "",
          genre:     research.genre          || "",
        })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Keyword generation failed.");
      const kws = Array.isArray(data.keywords) ? data.keywords : [];
      if (kws.length > 0) {
        setKeywords(kws);
        setLocalMsg(`${kws.length} keywords generated — review them, then click Search Bestsellers.`);
      }
    } catch (e) {
      setLocalMsg("Could not auto-generate keywords. Add them manually below.");
    } finally {
      setLoadingKeywords(false);
    }
  }

  function removeKeyword(kw) {
    setKeywords(keywords.filter((k) => k !== kw));
  }

  function addKeyword() {
    const kw = newKeyword.trim().toLowerCase();
    if (!kw) return;
    if (!keywords.includes(kw)) setKeywords([...keywords, kw]);
    setNewKeyword("");
    keywordInputRef.current?.focus();
  }

  function handleKeywordKeyDown(e) {
    if (e.key === "Enter") { e.preventDefault(); addKeyword(); }
  }

  async function runMultiSearch() {
    if (keywords.length === 0) {
      setLocalMsg("Add at least one keyword to search.");
      return;
    }
    setLoadingSearch(true);
    setSearchProgress(`Searching ${keywords.length} keyword${keywords.length !== 1 ? "s" : ""}…`);
    setLocalMsg("");
    try {
      const res = await fetch("/api/analysis/multi-search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ keywords, amazonDomain })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Search failed.");

      const rows = Array.isArray(data.books) ? data.books : [];
      const source = data.source || "ai_research";
      const isFallback = source === "open_library" || source === "ai_research";
      const bookSource = isFallback ? source : source === "scale_serp" ? "scale_serp" : "amazon";

      updateAnalysis((prev) => {
        const stamped = rows
          .filter((r) => r.title)
          .map((r) => ({ ...r, id: newBookId(), source: bookSource, expandedDetailsLoaded: Boolean(r.expandedDetailsLoaded) }));
        const bookKey = (b) => b.asin || b.url || "";
        const manualsOnly = prev.books.filter((b) => b.source === "manual");
        const manualKeys = new Set(manualsOnly.map(bookKey).filter(Boolean));
        const nextBooks = [...manualsOnly, ...stamped.filter((s) => !manualKeys.has(bookKey(s)))];
        return { ...prev, books: nextBooks, lastSearchQuery: keywords.join(", ") };
      });

      const sourceLabel = source === "open_library" ? "Open Library"
        : source === "ai_research" ? "AI Research"
        : source === "scale_serp" ? "Scale SERP"
        : "Amazon";

      const searched = data.keywordsSearched?.length || keywords.length;
      setLocalMsg(`${rows.length} competitors found across ${searched} keyword searches — sourced from ${sourceLabel}.`);
    } catch (e) {
      setLocalMsg(e.message || "Something went wrong.");
    } finally {
      setLoadingSearch(false);
      setSearchProgress("");
    }
  }

  async function expandBook(book) {
    if (!book.asin) { setLocalMsg("Expand details need an Amazon ASIN."); return; }
    if (expandedId === book.id) { setExpandedId(null); return; }
    setExpandedId(book.id);
    if (book.expandedDetailsLoaded) return;
    setLoadingProductId(book.id);
    setLocalMsg("");
    try {
      const res  = await fetch("/api/analysis/amazon-product", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ asin: book.asin, amazonDomain })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Could not load product details.");
      if (data.needsApiKey) { setLocalMsg(data.message || "Add RAINFOREST_API_KEY to load details."); return; }
      const d = data.details || {};
      patchBook(book.id, {
        title:               d.title              || book.title,
        subtitle:            d.subtitle           ?? book.subtitle,
        authors:             d.authors            ?? book.authors,
        thumbnail:           d.thumbnail          || book.thumbnail,
        rating:              d.rating             ?? book.rating,
        ratingsTotal:        d.ratingsTotal       ?? book.ratingsTotal,
        bestsellersRankFlat: d.bestsellersRankFlat ?? book.bestsellersRankFlat,
        bestsellersRanks:    d.bestsellersRanks   ?? book.bestsellersRanks,
        publicationDate:     d.publicationDate    ?? book.publicationDate,
        expandedDetailsLoaded: true
      });
    } catch (e) {
      setLocalMsg(e.message || "Expand failed.");
    } finally {
      setLoadingProductId(null);
    }
  }

  function addManualReference() {
    const url = manualUrl.trim();
    if (!url) { setLocalMsg("Paste an Amazon URL."); return; }
    const asin      = extractAsinFromAmazonUrl(url);
    const titleTrim = manualTitle.trim() || "Reference book";
    const d         = amazonDomain.replace(/^www\./, "");
    updateAnalysis((prev) => {
      const list = [...prev.books];
      const dup  = list.some((b) => (asin && b.asin === asin) || (!asin && b.url === url && b.source === "manual"));
      if (dup) return prev;
      list.push({
        id: newBookId(), source: "manual", asin,
        title: titleTrim,
        url: asin ? `https://www.${d}/dp/${asin}` : url,
        thumbnail: null, rating: null, ratingsTotal: null,
        bestsellersRankFlat: null, bestsellersRanks: null, expandedDetailsLoaded: false
      });
      return { ...prev, books: list };
    });
    setManualUrl(""); setManualTitle("");
    setLocalMsg("Reference added.");
  }

  async function generateIntelligence() {
    if (analysis.books.length === 0) {
      setIntelError("Add at least one competitor or reference book first, then generate intelligence.");
      return;
    }
    setIntelLoading(true);
    setIntelError("");
    try {
      const res = await fetch("/api/ai/competitive-intelligence", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          niche:          research.mainNicheLabel  || research.genre || "",
          subNiche:       research.subNicheLabel   || "",
          deepNiche:      research.deepNicheLabel  || "",
          bookTopic:      research.bookTopic       || "",
          stanceOnTopic:  research.stanceOnTopic   || "",
          standout:       research.standout        || "",
          publishingGoal: research.publishingGoal  || "",
          books: analysis.books.map((b) => ({
            title:               b.title,
            authors:             b.authors,
            subtitle:            b.subtitle,
            rating:              b.rating,
            ratingsTotal:        b.ratingsTotal,
            description:         b.description  || "",
            publicationDate:     b.publicationDate || "",
            bestsellersRankFlat: b.bestsellersRankFlat || "",
          }))
        })
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Intelligence generation failed.");

      const hasData =
        (data.readerPainPoints?.length > 0) ||
        (data.desiredOutcomes?.length > 0)  ||
        (Object.keys(data.targetAudience || {}).length > 0) ||
        (data.marketGaps?.length > 0);
      if (!hasData) throw new Error("AI returned an empty intelligence profile. Please try again.");

      updateAnalysis((prev) => ({ ...prev, intelligence: data }));

      if (!research.bookTopic?.trim() && updateResearch) {
        const seed =
          data.titleInsights?.recommendedTransformationPromise?.trim() ||
          data.titleInsights?.bestPositioningApproach?.trim() ||
          "";
        if (seed && seed.length >= 20) updateResearch({ bookTopic: seed });
      }

      if (data._partial && Array.isArray(data._missingFields) && data._missingFields.length) {
        setLocalMsg(`Intelligence extracted but incomplete — missing: ${data._missingFields.join(", ")}. Re-analyze for a full profile.`);
      } else {
        setLocalMsg("Market intelligence extracted — these signals will auto-fill your author tone, audience, and positioning throughout the book builder.");
      }
    } catch (e) {
      setIntelError(e.message || "Failed to generate intelligence. Try again.");
    } finally {
      setIntelLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-3xl">

      {/* ── Header ── */}
      <header>
        <p className="text-xs font-semibold uppercase tracking-wider text-sky-700/90">Step 2 — Competitive intelligence</p>
        <h2 className="mt-1 font-serif text-2xl font-bold text-slate-900 md:text-3xl">Competitive landscape</h2>
        <p className="mt-2 text-sm text-slate-600">
          Discover the strongest books in your market across multiple search angles, then let the AI extract your target audience, reader psychology, and positioning strategy.
        </p>
      </header>

      {errors?.form && (
        <p className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 text-sm text-rose-800">{errors.form}</p>
      )}

      {/* ── Keyword Discovery Engine ── */}
      <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Amazon Search Keywords</p>
            <p className="mt-0.5 text-sm text-slate-600">
              Each keyword runs a separate Amazon search. Results are merged and ranked by market strength.
            </p>
          </div>
          <button
            type="button"
            onClick={generateKeywords}
            disabled={loadingKeywords}
            className="shrink-0 rounded-full border border-slate-300 px-4 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50 transition-colors"
          >
            {loadingKeywords ? (
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-3 w-3 rounded-full border-2 border-slate-400 border-t-transparent animate-spin" />
                Generating…
              </span>
            ) : keywords.length > 0 ? "↺ Regenerate Keywords" : "Generate Keywords"}
          </button>
        </div>

        {/* Keyword chips */}
        <div className="mt-4 min-h-[3rem] flex flex-wrap gap-2 rounded-xl border border-slate-100 bg-slate-50 px-3 py-3">
          {loadingKeywords && keywords.length === 0 ? (
            <span className="text-xs text-slate-400 animate-pulse">Generating keywords from your book data…</span>
          ) : keywords.length === 0 ? (
            <span className="text-xs text-slate-400">No keywords yet — click "Generate Keywords" or type one below.</span>
          ) : (
            keywords.map((kw) => (
              <KeywordChip key={kw} keyword={kw} onRemove={removeKeyword} />
            ))
          )}
        </div>

        {/* Add keyword */}
        <div className="mt-3 flex gap-2">
          <input
            ref={keywordInputRef}
            className="input-light flex-1 text-sm"
            placeholder="Add a keyword and press Enter…"
            value={newKeyword}
            onChange={(e) => setNewKeyword(e.target.value)}
            onKeyDown={handleKeywordKeyDown}
          />
          <button
            type="button"
            onClick={addKeyword}
            disabled={!newKeyword.trim()}
            className="rounded-full border border-slate-300 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-40 transition-colors"
          >
            + Add
          </button>
        </div>

        {/* Search button */}
        <div className="mt-4 flex flex-wrap items-center gap-3">
          <button
            type="button"
            disabled={loadingSearch || keywords.length === 0}
            onClick={runMultiSearch}
            className="rounded-full bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-50 transition-colors"
          >
            {loadingSearch ? (
              <span className="flex items-center gap-2">
                <span className="inline-block h-3.5 w-3.5 rounded-full border-2 border-white border-t-transparent animate-spin" />
                {searchProgress || "Searching…"}
              </span>
            ) : (
              `Search Bestsellers${keywords.length > 0 ? ` (${keywords.length} keyword${keywords.length !== 1 ? "s" : ""})` : ""}`
            )}
          </button>
          {keywords.length > 0 && (
            <p className="text-xs text-slate-500">
              Searches all keywords · merges results · removes duplicates · ranks by market strength
            </p>
          )}
        </div>
      </div>

      {localMsg && (
        <p className={`mt-4 text-sm ${localMsg.includes("intelligence extracted") || localMsg.includes("competitors found") ? "font-medium text-emerald-700" : "text-slate-600"}`}>
          {localMsg}
        </p>
      )}

      {/* ── Book list ── */}
      {analysis.books.length > 0 && (
        <div className="mt-2 flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <p className="text-sm font-medium text-slate-700">{analysis.books.length} competitor book{analysis.books.length !== 1 ? "s" : ""} found</p>
            <button
              type="button"
              onClick={() => setShowBooks((v) => !v)}
              className="rounded-full border border-slate-200 px-2.5 py-0.5 text-[11px] font-medium text-slate-500 hover:bg-slate-50 transition-colors"
            >
              {showBooks ? "Hide" : "Show"}
            </button>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5">
              <p className="text-[11px] text-slate-400">Sort:</p>
              {[
                { value: "default",  label: "Default" },
                { value: "rating",   label: "Rating" },
                { value: "reviews",  label: "Reviews" },
                { value: "rank",     label: "Rank" },
              ].map(({ value, label }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => setSortBy(value)}
                  className={`rounded-full px-2.5 py-0.5 text-[11px] font-medium transition-colors ${
                    sortBy === value
                      ? "bg-slate-800 text-white"
                      : "border border-slate-200 text-slate-500 hover:bg-slate-50"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
            {analysis.books.filter(b => b.source !== "manual").length > 0 && (
              <button
                type="button"
                onClick={() => updateAnalysis((prev) => ({ ...prev, books: prev.books.filter(b => b.source === "manual") }))}
                className="text-xs text-rose-600 hover:underline"
              >
                Clear all
              </button>
            )}
          </div>
        </div>
      )}

      {showBooks && <ul className="mt-3 space-y-3">
        {analysis.books.length === 0 && (
          <li className="rounded-2xl border border-dashed border-slate-200 bg-white/80 px-4 py-8 text-center text-sm text-slate-500">
            No competitors yet — search above or paste a URL below.
          </li>
        )}
        {[...analysis.books].sort((a, b) => {
          if (sortBy === "rating")  return (b.rating ?? -1) - (a.rating ?? -1);
          if (sortBy === "reviews") return (b.ratingsTotal ?? -1) - (a.ratingsTotal ?? -1);
          if (sortBy === "rank") {
            const ra = typeof a.bestsellersRankFlat === "string" ? parseInt(a.bestsellersRankFlat.replace(/\D/g, ""), 10) || Infinity : Infinity;
            const rb = typeof b.bestsellersRankFlat === "string" ? parseInt(b.bestsellersRankFlat.replace(/\D/g, ""), 10) || Infinity : Infinity;
            return ra - rb;
          }
          return 0;
        }).map((book) => {
          const isOpen        = expandedId === book.id;
          const ratingLabel   = typeof book.rating       === "number" ? `${book.rating.toFixed(1)} ★` : null;
          const reviewsLabel  = typeof book.ratingsTotal === "number" ? `${book.ratingsTotal.toLocaleString()} reviews` : null;
          const matchedKws    = Array.isArray(book._matchedKeywords) ? book._matchedKeywords : [];
          return (
            <li key={book.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="flex gap-4 p-4">
                {book.thumbnail ? (
                  <img src={book.thumbnail} alt="" className="h-28 w-[4.85rem] shrink-0 rounded-lg object-cover" />
                ) : (
                  <div className="flex h-28 w-[4.85rem] shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs text-slate-400">
                    No cover
                  </div>
                )}
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-start gap-2">
                    <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ${
                      book.source === "manual"       ? "bg-amber-100 text-amber-900"
                      : book.source === "open_library" ? "bg-emerald-100 text-emerald-800"
                      : book.source === "ai_research"  ? "bg-violet-100 text-violet-800"
                      : book.source === "scale_serp"   ? "bg-sky-100 text-sky-800"
                      : "bg-slate-100 text-slate-700"
                    }`}>
                      {book.source === "manual"       ? "Your reference"
                        : book.source === "open_library" ? "Open Library"
                        : book.source === "ai_research"  ? "AI Research"
                        : book.source === "scale_serp"   ? "Amazon"
                        : "Amazon"}
                    </span>
                    {matchedKws.length > 1 && (
                      <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-800">
                        {matchedKws.length} keyword matches
                      </span>
                    )}
                  </div>
                  <p className="mt-1 font-semibold leading-snug text-slate-900">{book.title}</p>
                  {book.authors && <p className="mt-1 text-xs text-slate-600">{book.authors}</p>}
                  {(ratingLabel || reviewsLabel) && (
                    <p className="mt-1 text-xs text-slate-600">
                      {[ratingLabel, reviewsLabel].filter(Boolean).join(" · ")}
                      {book.bestsellerBadge?.category && <span className="ml-2 text-amber-800">· Bestseller badge</span>}
                    </p>
                  )}
                  <a href={book.url} target="_blank" rel="noreferrer" className="mt-2 inline-block truncate text-xs text-sky-700 hover:underline">
                    {book.url}
                  </a>
                  <div className="mt-3 flex flex-wrap gap-2">
                    <button
                      type="button"
                      onClick={() => expandBook(book)}
                      className="rounded-full border border-slate-300 px-3 py-1 text-xs font-medium text-slate-800 hover:bg-slate-50"
                    >
                      {loadingProductId === book.id ? "Loading…" : isOpen ? "Collapse" : "Expand details"}
                    </button>
                    <button
                      type="button"
                      onClick={() => removeBook(book.id)}
                      className="rounded-full border border-slate-200 px-3 py-1 text-xs font-medium text-rose-700 hover:bg-rose-50"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              </div>
              {isOpen && (
                <div className="border-t border-slate-100 bg-slate-50 px-4 py-4 text-sm text-slate-700">
                  {book.publicationDate && <p><span className="font-medium text-slate-900">Published:</span> {book.publicationDate}</p>}
                  {book.subtitle && <p className="mt-1"><span className="font-medium text-slate-900">Subtitle:</span> {book.subtitle}</p>}
                  <p className="mt-2">
                    <span className="font-medium text-slate-900">Rating:</span>{" "}
                    {ratingLabel ? ratingLabel : "—"}{reviewsLabel ? ` (${reviewsLabel})` : ""}
                  </p>
                  <p className="mt-2 font-medium text-slate-900">Bestseller rank</p>
                  {book.bestsellersRankFlat ? (
                    <p className="text-slate-700">{book.bestsellersRankFlat}</p>
                  ) : (
                    <p className="text-slate-500">Expand pulls rank when API key is set.</p>
                  )}
                  {Array.isArray(book.bestsellersRanks) && book.bestsellersRanks.length > 0 && (
                    <ul className="mt-2 space-y-1 text-xs">
                      {book.bestsellersRanks.map((row, i) => (
                        <li key={i}>
                          #{row.rank} in {row.category}
                          {row.link && <a className="ml-2 text-sky-700 hover:underline" href={row.link} target="_blank" rel="noreferrer">View ranking</a>}
                        </li>
                      ))}
                    </ul>
                  )}
                  {matchedKws.length > 0 && (
                    <div className="mt-3">
                      <p className="font-medium text-slate-900">Found via keywords</p>
                      <div className="mt-1 flex flex-wrap gap-1.5">
                        {matchedKws.map((kw) => (
                          <span key={kw} className="rounded-full bg-sky-50 border border-sky-200 px-2 py-0.5 text-[10px] text-sky-700">{kw}</span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </li>
          );
        })}
      </ul>}

      {/* ── Add manual reference ── */}
      <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="font-serif text-lg font-semibold text-slate-900">Add your reference copy</h3>
        <p className="mt-1 text-xs text-slate-600">
          Paste any Amazon paperback or Kindle listing URL. Optionally name it.
        </p>
        <div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]">
          <input
            className="input-light"
            placeholder="https://www.amazon.com/dp/…"
            value={manualUrl}
            onChange={(e) => setManualUrl(e.target.value)}
          />
          <input
            className="input-light"
            placeholder="Optional display title"
            value={manualTitle}
            onChange={(e) => setManualTitle(e.target.value)}
          />
          <button
            type="button"
            onClick={addManualReference}
            className="rounded-full bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800"
          >
            Add URL
          </button>
        </div>
      </div>

      {/* ── Intelligence Engine ── */}
      <div className="mt-10 rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-50/70 via-white to-violet-50/40 p-6 shadow-sm">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-indigo-700">
              Competitive Intelligence Engine
            </p>
            <h3 className="mt-1 font-serif text-xl font-semibold text-slate-900">
              AI Market Analysis
            </h3>
            <p className="mt-1.5 max-w-xl text-sm leading-relaxed text-slate-600">
              Once your competitor books are loaded, the AI analyzes them to extract your target audience, reader pain profile, ideal tone, positioning strategy, and more.
              These signals auto-fill your author persona, outline, and all downstream steps.
            </p>
          </div>
          <button
            type="button"
            onClick={generateIntelligence}
            disabled={intelLoading || analysis.books.length === 0}
            className="shrink-0 rounded-full bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-md transition hover:from-indigo-500 hover:to-violet-500 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {intelLoading ? "Analyzing…" : intelligence ? "Re-analyze" : "Analyze Competitors"}
          </button>
        </div>

        {intelLoading && (
          <div className="mt-4 rounded-xl border border-indigo-100 bg-indigo-50/60 px-4 py-3">
            <p className="text-sm font-semibold text-indigo-700 animate-pulse">
              AI extracting market intelligence from {analysis.books.length} competitor book{analysis.books.length !== 1 ? "s" : ""}…
            </p>
          </div>
        )}

        {intelError && (
          <p className="mt-3 text-sm font-medium text-rose-700">{intelError}</p>
        )}

        {intelligence && !intelLoading && (
          <div className="mt-5 space-y-4">
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-500" />
              <p className="text-xs font-bold uppercase tracking-wider text-emerald-700">
                Intelligence extracted — auto-filling all downstream steps
              </p>
            </div>

            {isNewIntel ? (() => {
              const ta    = intelligence.targetAudience             || {};
              const ppts  = intelligence.readerPainPoints           || [];
              const outs  = intelligence.desiredOutcomes            || [];
              const gaps  = intelligence.marketGaps                 || [];
              const strats= intelligence.positioningStrategies      || [];
              const usps  = intelligence.uniqueSellingPropositions  || [];
              const ti    = intelligence.titleInsights              || {};
              const apg   = intelligence.authorPersonaGuidance      || {};
              const brief = intelligence.outlineGenerationBrief     || "";
              const rpp   = intelligence.readerPsychologyProfile    || {};
              const mp    = intelligence.marketPatterns             || {};
              const csw   = intelligence.competitorStrengthsWeaknesses || [];
              const scores= intelligence.researchScores             || {};
              const recs  = intelligence.priorityRecommendations    || [];
              const strVal = (v) => typeof v === "string" ? v : (Array.isArray(v) ? v.join("; ") : (v && typeof v === "object" ? Object.values(v).filter(Boolean).join(" · ") : ""));
              return (
                <div className="space-y-4">
                  {Object.keys(ta).length > 0 && (
                    <div className="rounded-xl border border-slate-200 bg-white p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-3">Target Audience</p>
                      <div className="grid gap-2 sm:grid-cols-2">
                        {ta.primary         && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Primary</p><p className="text-sm text-slate-800 leading-snug">{ta.primary}</p></div>}
                        {ta.secondary       && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Secondary</p><p className="text-sm text-slate-800 leading-snug">{ta.secondary}</p></div>}
                        {ta.experienceLevel && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Experience</p><p className="text-sm text-slate-800 leading-snug">{ta.experienceLevel}</p></div>}
                        {ta.demographics    && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Demographics</p><p className="text-sm text-slate-800 leading-snug">{ta.demographics}</p></div>}
                      </div>
                      {ta.motivations && <div className="mt-2 border-t border-slate-100 pt-2"><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Motivations</p><p className="text-sm text-slate-700 leading-snug">{ta.motivations}</p></div>}
                    </div>
                  )}

                  {(ppts.length > 0 || outs.length > 0) && (
                    <div className="grid gap-3 sm:grid-cols-2">
                      {ppts.length > 0 && (
                        <div className="rounded-xl border border-slate-200 bg-white p-4">
                          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">Reader Pain Points</p>
                          <ul className="space-y-1">
                            {ppts.slice(0, 7).map((p, i) => (
                              <li key={i} className="flex gap-1.5 text-sm text-slate-700"><span className="text-rose-400 shrink-0 mt-0.5">•</span><span>{String(p)}</span></li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {outs.length > 0 && (
                        <div className="rounded-xl border border-slate-200 bg-white p-4">
                          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">Desired Outcomes</p>
                          <ul className="space-y-1">
                            {outs.slice(0, 7).map((o, i) => (
                              <li key={i} className="flex gap-1.5 text-sm text-slate-700"><span className="text-emerald-400 shrink-0 mt-0.5">•</span><span>{String(o)}</span></li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}

                  {gaps.length > 0 && (
                    <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-amber-700 mb-2">Market Gaps</p>
                      <ul className="space-y-1">
                        {gaps.slice(0, 5).map((g, i) => (
                          <li key={i} className="flex gap-1.5 text-sm text-amber-900"><span className="text-amber-500 shrink-0 mt-0.5">◆</span><span>{String(g)}</span></li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {strats.length > 0 && (
                    <div>
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">Positioning Strategies</p>
                      <div className="flex flex-wrap gap-2">
                        {strats.map((s, i) => {
                          const label = typeof s === "string" ? s : (s.angle || s.name || s.strategy || Object.values(s)[0] || "");
                          return <span key={i} className="rounded-full bg-sky-100 px-3 py-1 text-xs font-medium text-sky-800">{String(label)}</span>;
                        })}
                      </div>
                    </div>
                  )}

                  {usps.length > 0 && (
                    <div>
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">Unique Selling Propositions</p>
                      <div className="grid gap-2 sm:grid-cols-2">
                        {usps.slice(0, 4).map((u, i) => {
                          const statement = typeof u === "string" ? u : (u.statement || u.usp || Object.values(u)[0] || "");
                          const why = typeof u === "object" ? (u.whyItStandsOut || u.whyReadersCare || u.why || "") : "";
                          return (
                            <div key={i} className="rounded-xl border border-violet-200 bg-violet-50/60 p-3">
                              <p className="text-sm font-semibold text-violet-900 leading-snug">{String(statement)}</p>
                              {why && <p className="mt-1 text-xs text-violet-700 leading-snug">{why}</p>}
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}

                  {(Object.keys(ti).length > 0 || Object.keys(apg).length > 0) && (
                    <div className="grid gap-3 sm:grid-cols-2">
                      {ti.bestTitleStyle                       && <IntelChip label="Best Title Style"         value={strVal(ti.bestTitleStyle)} />}
                      {ti.bestSubtitleStyle                    && <IntelChip label="Best Subtitle Style"       value={strVal(ti.bestSubtitleStyle)} />}
                      {ti.recommendedTransformationPromise     && <IntelChip label="Transformation Promise"    value={strVal(ti.recommendedTransformationPromise)} />}
                      {ti.bestPositioningApproach              && <IntelChip label="Positioning Approach"      value={strVal(ti.bestPositioningApproach)} />}
                      {apg.tone                                && <IntelChip label="Recommended Tone"          value={strVal(apg.tone)} />}
                      {apg.authorVoice                         && <IntelChip label="Author Voice"              value={strVal(apg.authorVoice)} />}
                      {apg.credibilityStyle                    && <IntelChip label="Credibility Style"         value={strVal(apg.credibilityStyle)} />}
                      {apg.writingApproach                     && <IntelChip label="Writing Approach"          value={strVal(apg.writingApproach)} />}
                    </div>
                  )}

                  {!!strVal(brief) && (
                    <div className="rounded-xl border border-indigo-200 bg-indigo-50/60 p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 mb-2">Outline Generation Brief</p>
                      <p className="text-sm text-slate-800 leading-relaxed">{strVal(brief)}</p>
                    </div>
                  )}

                  {/* ── Book DNA ── */}
                  {(intelligence.readerPainProfile || intelligence.transformationPromise || intelligence.energyStyle || intelligence.writingStyleFingerprint || intelligence.positioningStrategy) && (
                    <div className="rounded-xl border border-slate-200 bg-white p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-3">Book DNA</p>
                      <div className="space-y-3">
                        {intelligence.readerPainProfile     && <div><p className="text-[9px] font-bold uppercase text-rose-400 mb-0.5">Reader Pain Profile</p><p className="text-sm text-slate-700 leading-snug">{intelligence.readerPainProfile}</p></div>}
                        {intelligence.transformationPromise && <div><p className="text-[9px] font-bold uppercase text-emerald-500 mb-0.5">Transformation Promise</p><p className="text-sm text-slate-700 leading-snug">{intelligence.transformationPromise}</p></div>}
                        {intelligence.energyStyle           && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Energy Style</p><p className="text-sm text-slate-700 leading-snug">{intelligence.energyStyle}</p></div>}
                        {intelligence.writingStyleFingerprint && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Writing Style Fingerprint</p><p className="text-sm text-slate-700 leading-snug">{intelligence.writingStyleFingerprint}</p></div>}
                        {intelligence.positioningStrategy   && <div><p className="text-[9px] font-bold uppercase text-violet-500 mb-0.5">Positioning Strategy</p><p className="text-sm text-slate-700 leading-snug">{intelligence.positioningStrategy}</p></div>}
                      </div>
                      {Array.isArray(intelligence.emotionalTriggers) && intelligence.emotionalTriggers.length > 0 && (
                        <div className="mt-3 border-t border-slate-100 pt-3">
                          <p className="text-[9px] font-bold uppercase text-violet-400 mb-1.5">Emotional Triggers</p>
                          <div className="flex flex-wrap gap-1.5">
                            {intelligence.emotionalTriggers.map((t, i) => (
                              <span key={i} className="rounded-full bg-violet-100 px-2.5 py-0.5 text-xs font-medium text-violet-800">{String(t)}</span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* ── Reader Psychology Profile ── */}
                  {Object.keys(rpp).length > 0 && (
                    <div className="rounded-xl border border-rose-200 bg-rose-50/40 p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-rose-600 mb-3">Reader Psychology Profile</p>
                      <div className="grid gap-3 sm:grid-cols-2">
                        {rpp.currentSituation    && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Current Situation</p><p className="text-xs text-slate-700 leading-snug">{rpp.currentSituation}</p></div>}
                        {rpp.desiredFuture       && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Desired Future</p><p className="text-xs text-slate-700 leading-snug">{rpp.desiredFuture}</p></div>}
                        {rpp.internalObstacles   && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Internal Obstacles</p><p className="text-xs text-slate-700 leading-snug">{rpp.internalObstacles}</p></div>}
                        {rpp.externalObstacles   && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">External Obstacles</p><p className="text-xs text-slate-700 leading-snug">{rpp.externalObstacles}</p></div>}
                        {rpp.falseBeliefsToBreak && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">False Beliefs to Break</p><p className="text-xs text-slate-700 leading-snug">{rpp.falseBeliefsToBreak}</p></div>}
                        {rpp.learningPreferences && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Learning Preferences</p><p className="text-xs text-slate-700 leading-snug">{rpp.learningPreferences}</p></div>}
                        {rpp.emotionalDrivers    && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Emotional Drivers</p><p className="text-xs text-slate-700 leading-snug">{rpp.emotionalDrivers}</p></div>}
                        {rpp.commonMistakes      && <div><p className="text-[9px] font-bold uppercase text-slate-400 mb-0.5">Common Mistakes</p><p className="text-xs text-slate-700 leading-snug">{rpp.commonMistakes}</p></div>}
                      </div>
                    </div>
                  )}

                  {/* ── Market Patterns ── */}
                  {Object.keys(mp).length > 0 && (
                    <div className="rounded-xl border border-amber-200 bg-amber-50/40 p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-amber-700 mb-3">Market Patterns</p>
                      <div className="space-y-3">
                        {Array.isArray(mp.topicsEverySuccessfulBookCovers) && mp.topicsEverySuccessfulBookCovers.length > 0 && (
                          <div>
                            <p className="text-[9px] font-bold uppercase text-slate-400 mb-1.5">Table Stakes (must cover)</p>
                            <div className="flex flex-wrap gap-1.5">
                              {mp.topicsEverySuccessfulBookCovers.map((t, i) => (
                                <span key={i} className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-xs font-medium text-emerald-800">{String(t)}</span>
                              ))}
                            </div>
                          </div>
                        )}
                        {Array.isArray(mp.overusedFrameworks) && mp.overusedFrameworks.length > 0 && (
                          <div>
                            <p className="text-[9px] font-bold uppercase text-slate-400 mb-1.5">Overused / Readers Are Tired Of</p>
                            <div className="flex flex-wrap gap-1.5">
                              {mp.overusedFrameworks.map((t, i) => (
                                <span key={i} className="rounded-full bg-rose-100 px-2.5 py-0.5 text-xs font-medium text-rose-700">{String(t)}</span>
                              ))}
                            </div>
                          </div>
                        )}
                        {Array.isArray(mp.underservedTopics) && mp.underservedTopics.length > 0 && (
                          <div>
                            <p className="text-[9px] font-bold uppercase text-slate-400 mb-1.5">Underserved Opportunities</p>
                            <div className="flex flex-wrap gap-1.5">
                              {mp.underservedTopics.map((t, i) => (
                                <span key={i} className="rounded-full bg-amber-100 px-2.5 py-0.5 text-xs font-medium text-amber-800">{String(t)}</span>
                              ))}
                            </div>
                          </div>
                        )}
                        {Array.isArray(mp.emergingTrends) && mp.emergingTrends.length > 0 && (
                          <div>
                            <p className="text-[9px] font-bold uppercase text-slate-400 mb-1.5">Emerging Trends</p>
                            <div className="flex flex-wrap gap-1.5">
                              {mp.emergingTrends.map((t, i) => (
                                <span key={i} className="rounded-full bg-sky-100 px-2.5 py-0.5 text-xs font-medium text-sky-800">{String(t)}</span>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {/* ── Competitor Strengths & Weaknesses ── */}
                  {csw.length > 0 && (
                    <div className="rounded-xl border border-slate-200 bg-white p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-3">Competitor Analysis</p>
                      <div className="space-y-3">
                        {csw.slice(0, 5).map((c, i) => (
                          <div key={i} className="rounded-lg border border-slate-100 bg-slate-50 p-3">
                            <p className="text-xs font-semibold text-slate-900 mb-2">"{String(c.title || "")}"</p>
                            <div className="grid gap-2 sm:grid-cols-3">
                              {Array.isArray(c.likelyStrengths) && c.likelyStrengths.length > 0 && (
                                <div>
                                  <p className="text-[9px] font-bold uppercase text-emerald-600 mb-1">Strengths</p>
                                  <ul className="space-y-0.5">{c.likelyStrengths.map((s, j) => <li key={j} className="text-[11px] text-slate-600 leading-snug">• {String(s)}</li>)}</ul>
                                </div>
                              )}
                              {Array.isArray(c.likelyWeaknesses) && c.likelyWeaknesses.length > 0 && (
                                <div>
                                  <p className="text-[9px] font-bold uppercase text-rose-500 mb-1">Weaknesses</p>
                                  <ul className="space-y-0.5">{c.likelyWeaknesses.map((s, j) => <li key={j} className="text-[11px] text-slate-600 leading-snug">• {String(s)}</li>)}</ul>
                                </div>
                              )}
                              {Array.isArray(c.likelyReaderComplaints) && c.likelyReaderComplaints.length > 0 && (
                                <div>
                                  <p className="text-[9px] font-bold uppercase text-amber-600 mb-1">Reader Complaints</p>
                                  <ul className="space-y-0.5">{c.likelyReaderComplaints.map((s, j) => <li key={j} className="text-[11px] text-slate-600 leading-snug">• {String(s)}</li>)}</ul>
                                </div>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* ── Research Scores ── */}
                  {Object.keys(scores).length > 0 && (
                    <div className="rounded-xl border border-slate-200 bg-white p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-3">Research Quality Scores</p>
                      <div className="space-y-2">
                        {[
                          { key: "competitorCoverage",  label: "Competitor Coverage",   color: "bg-sky-500" },
                          { key: "readerUnderstanding", label: "Reader Understanding",  color: "bg-violet-500" },
                          { key: "marketUnderstanding", label: "Market Understanding",  color: "bg-indigo-500" },
                          { key: "commercialOpportunity", label: "Commercial Opportunity", color: "bg-emerald-500" },
                          { key: "confidence",          label: "Overall Confidence",    color: "bg-slate-600" },
                        ].map(({ key, label, color }) => {
                          const val = typeof scores[key] === "number" ? Math.min(100, Math.max(0, scores[key])) : null;
                          if (val === null) return null;
                          return (
                            <div key={key} className="flex items-center gap-3">
                              <p className="w-40 shrink-0 text-[11px] text-slate-600">{label}</p>
                              <div className="flex-1 h-1.5 rounded-full bg-slate-100">
                                <div className={`h-full rounded-full ${color}`} style={{ width: `${val}%` }} />
                              </div>
                              <p className="w-8 text-right text-[11px] font-semibold text-slate-700">{val}</p>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}

                  {/* ── Priority Recommendations ── */}
                  {recs.length > 0 && (
                    <div className="rounded-xl border border-indigo-200 bg-indigo-50/60 p-4">
                      <p className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 mb-2">Priority Recommendations</p>
                      <ol className="space-y-1.5">
                        {recs.slice(0, 5).map((r, i) => (
                          <li key={i} className="flex gap-2 text-sm text-slate-800 leading-snug">
                            <span className="shrink-0 font-bold text-indigo-500">{i + 1}.</span>
                            <span>{String(r)}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}
                </div>
              );
            })() : (
              <div className="space-y-4">
                <div className="grid gap-3 sm:grid-cols-2">
                  <IntelChip label="Target Audience"        value={intelligence.targetAudience} />
                  <IntelChip label="Energy Style"           value={intelligence.energyStyle} />
                  <IntelChip label="Reader Pain Profile"    value={intelligence.readerPainProfile} />
                  <IntelChip label="Transformation Promise" value={intelligence.transformationPromise} />
                </div>
                <IntelTags label="Recommended Author Tones" values={intelligence.authorTones}      colorClass="bg-sky-100 text-sky-800" />
                <IntelTags label="Emotional Triggers"       values={intelligence.emotionalTriggers} colorClass="bg-violet-100 text-violet-800" />
                <div className="grid gap-3 sm:grid-cols-2">
                  <IntelChip label="Tone Recommendation"  value={intelligence.toneRecommendation} />
                  <IntelChip label="Writing Style"        value={intelligence.writingStyleFingerprint} />
                  <IntelChip label="Positioning Strategy" value={intelligence.positioningStrategy} />
                  <IntelChip label="Market Gap"           value={intelligence.marketGapAnalysis} />
                </div>
                {intelligence.bestsellerDNA && (
                  <div className="rounded-xl border border-amber-200 bg-amber-50/60 px-4 py-3">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-amber-700 mb-1">Bestseller DNA</p>
                    <p className="text-sm text-slate-800 leading-snug">{intelligence.bestsellerDNA}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {!intelligence && !intelLoading && analysis.books.length === 0 && (
          <p className="mt-4 rounded-xl border border-dashed border-indigo-200 bg-white/60 px-4 py-3 text-sm text-slate-500">
            Search for competitors above, then click <span className="font-semibold">Analyze Competitors</span> to generate your publishing intelligence profile.
          </p>
        )}

        {!intelligence && !intelLoading && analysis.books.length > 0 && (
          <p className="mt-4 rounded-xl border border-indigo-100 bg-white/70 px-4 py-3 text-sm text-slate-600">
            {analysis.books.length} book{analysis.books.length !== 1 ? "s" : ""} ready — click{" "}
            <span className="font-semibold text-indigo-700">Analyze Competitors</span> to extract your market intelligence.
          </p>
        )}
      </div>

    </div>
  );
}
