/** Default niche catalog — 6 main niches × 10 sub-niches each */

function sub(id, label, contentDirection) {
  return { id, label, blueprintKey: "self-help-transformation", contentDirection, deepNiches: [] };
}

export const DEFAULT_NICHE_REGISTRY = {
  version: 2,
  mainNiches: [
    {
      id: "self-help",
      label: "Self-Help",
      description: "Transformation, mindset, personal development, emotional growth, and practical self-improvement systems.",
      tones: ["Empathetic", "Direct & practical", "Authoritative", "Reflective", "Motivating"],
      audiences: ["Busy professionals", "Students", "People in transition", "Burned-out achievers", "First-time self-improvement readers"],
      publishingGoals: ["Amazon KDP bestseller", "Authority building", "Course funnel", "Newsletter growth"],
      subNiches: [
        sub("overthinking", "Overthinking",
          "Compassionate and insight-driven. Guides readers through recognizing chronic thought loops, reframing anxious patterns, and adopting clarity-based decision-making. Progressive pacing moves from awareness to tools to daily mental practice, with each chapter building quieter, more intentional thinking. Ideal reader outcome: the ability to interrupt overthinking in real time and move forward with confidence."),
        sub("confidence-building", "Confidence Building",
          "Encouraging and action-oriented. Guides readers from persistent self-doubt to bold self-expression through incremental challenges and mindset reframes. Each chapter builds on tangible real-world confidence wins, progressing from inner narrative shifts to visible behavioral change. Ideal reader outcome: a reader who acts despite fear and trusts themselves in high-stakes situations."),
        sub("emotional-intelligence", "Emotional Intelligence",
          "Reflective and warm. Develops readers' ability to recognize, understand, and manage emotions in themselves and others. Pacing alternates between self-assessment exercises and interpersonal skill-building, with each chapter adding a new emotional competency. Ideal reader outcome: deeper relationships, better conflict resolution, and stronger self-awareness in daily life."),
        sub("self-discipline", "Self-Discipline",
          "Direct and motivating. Converts abstract willpower into concrete daily systems that work without relying on motivation. Pacing follows a build-up from habit design to environmental architecture to identity-level discipline. Chapters are structured around implementation, not inspiration. Ideal reader outcome: a reader who executes consistently, even on low-energy days."),
        sub("mental-toughness", "Mental Toughness",
          "Bold and resilience-focused. Trains readers to perform under pressure, recover from setbacks, and build an unbreakable inner core. Chapters use challenge-based frameworks and adversity reframing drawn from elite performance psychology. Pacing escalates from mindset audits to high-pressure scenario training. Ideal reader outcome: composure and resolve in the face of difficulty."),
        sub("resilience", "Resilience",
          "Empathetic and empowering. Guides readers through adversity, loss, and change with science-backed recovery frameworks and personal growth perspectives. Pacing moves from acknowledging pain to processing it to rebuilding with new strength. Chapters balance emotional validation with actionable post-traumatic growth strategies. Ideal reader outcome: the capacity to recover faster and grow stronger from setbacks."),
        sub("habit-formation", "Habit Formation",
          "Practical and systematic. Breaks down the neuroscience of behavior change into actionable daily routines. Each chapter introduces a new layer of the habit loop with specific implementation exercises and failure-proofing strategies. Pacing builds progressively from understanding triggers to designing environments that make habits automatic. Ideal reader outcome: a sustainable personal system of high-value habits."),
        sub("self-esteem", "Self-Esteem",
          "Nurturing and affirming. Helps readers dismantle deeply rooted negative self-beliefs and rebuild genuine, unshakeable self-worth. Combines therapeutic insight with daily practice, moving from inner critic awareness to self-compassion to confident self-expression. Pacing is gradual and safe, honoring emotional depth. Ideal reader outcome: a reader who values themselves regardless of external validation."),
        sub("positive-psychology", "Positive Psychology",
          "Optimistic and scientifically grounded. Introduces evidence-based strategies for flourishing, gratitude, flow states, and meaning-making. Pacing alternates between research insights and experiential exercises that readers can apply the same day. Chapters build a personal wellbeing architecture grounded in peer-reviewed science. Ideal reader outcome: a measurable increase in daily happiness, purpose, and engagement."),
        sub("personal-growth", "Personal Growth",
          "Expansive and vision-driven. Helps readers audit their current life, clarify core values, and design intentional growth paths aligned with who they want to become. Chapters progress from self-awareness to goal architecture to consistent action. Pacing balances introspective depth with forward momentum. Ideal reader outcome: a reader living with intention, progressing toward a version of themselves they deeply respect.")
      ]
    },
    {
      id: "business-money",
      label: "Business & Money",
      description: "Entrepreneurship, wealth creation, business growth, financial freedom, and income-generating strategies.",
      tones: ["Practical", "Strategic", "Execution-focused", "Direct & analytical", "Persuasive"],
      audiences: ["Entrepreneurs", "Freelancers", "Side-hustle builders", "Aspiring investors", "9-to-5 escape artists"],
      publishingGoals: ["Amazon KDP bestseller", "Lead generation", "Authority positioning", "High-ticket coaching funnel"],
      subNiches: [
        sub("small-business", "Small Business",
          "Practical and grounded. Covers the fundamentals of launching, running, and growing a small business with actionable systems for real operators. Each chapter solves a specific operational challenge with real-world examples, checklists, and templates. Pacing follows the business lifecycle from idea to sustainable operation. Ideal reader outcome: a reader who runs their business like a professional, not a hobbyist."),
        sub("entrepreneurship", "Entrepreneurship",
          "Energetic and strategic. Guides aspiring entrepreneurs from raw idea to validated execution with frameworks for testing, launching, and scaling. Pacing follows the startup journey chronologically — from mindset to market fit to growth levers. Chapters combine strategic thinking with immediate action steps. Ideal reader outcome: a reader who has launched, learned, and built something real."),
        sub("passive-income", "Passive Income",
          "Aspirational and tactical. Demystifies the income streams that earn money while the reader sleeps. Chapters move from income stream selection to system setup to automation and long-term optimization. Pacing is goal-first, showing readers what financial freedom looks like before building the path toward it. Ideal reader outcome: at least one operational passive income stream generating consistent monthly revenue."),
        sub("side-hustles", "Side Hustles",
          "Accessible and motivating. Lowers the barrier to starting a profitable side income without quitting the day job. Pacing covers idea selection, fast launch strategy, first revenue milestone, and scaling toward independence. Chapters are concise and action-first. Ideal reader outcome: a reader who has earned their first dollar outside their salary and has a clear roadmap to grow it."),
        sub("financial-independence", "Financial Independence",
          "Liberating and long-term focused. Builds the mental models and financial systems needed to escape the paycheck cycle permanently. Chapters progress from financial literacy to investment strategy to lifestyle design and early retirement planning. Pacing balances inspiring vision with rigorous, personalized calculation. Ideal reader outcome: a clear FI number, a savings rate, and a step-by-step investment plan."),
        sub("investing-for-beginners", "Investing for Beginners",
          "Clear, patient, and confidence-building. Removes all intimidation from investing with step-by-step guidance on accounts, asset classes, and long-term strategy. Pacing moves from financial fundamentals to first investment action in a structured sequence. Chapters use plain language with no jargon. Ideal reader outcome: an active investment account with a diversified portfolio and a clear long-term strategy."),
        sub("sales-skills", "Sales Skills",
          "Direct and results-driven. Teaches persuasion, objection handling, rapport-building, and closing techniques grounded in human psychology. Each chapter builds a specific sales skill with practice scripts, roleplay scenarios, and real-world application. Pacing follows the full sales cycle from first contact to closed deal. Ideal reader outcome: a reader who can sell confidently, ethically, and at a high conversion rate."),
        sub("business-systems", "Business Systems",
          "Operational and efficiency-focused. Shows business owners how to remove themselves from daily firefighting through automation, delegation frameworks, and documented processes. Pacing follows a systemization roadmap — audit, document, automate, delegate. Chapters deliver plug-and-play SOPs and workflow templates. Ideal reader outcome: a business that runs without the owner's constant presence."),
        sub("wealth-mindset", "Wealth Mindset",
          "Transformational and mindset-first. Identifies and rewires the limiting beliefs about money, success, and abundance that keep readers stuck. Chapters alternate between deep belief audits and concrete wealth-building behavioral changes. Pacing moves from psychological diagnosis to identity reconstruction to aligned financial action. Ideal reader outcome: a reader whose relationship with money is expansive, intentional, and empowering."),
        sub("online-business", "Online Business",
          "Modern and opportunity-focused. Covers the full ecosystem of digital income from content creation to e-commerce to service-based business. Pacing maps the complete online business journey from first idea to profitable, scalable operation. Chapters combine market research with platform-specific strategy. Ideal reader outcome: a running online business generating real revenue with a clear growth roadmap.")
      ]
    },
    {
      id: "health-fitness-dieting",
      label: "Health, Fitness & Dieting",
      description: "Physical wellness, nutrition, longevity, energy optimization, and healthy lifestyle improvement.",
      tones: ["Empowering", "Scientific yet accessible", "Compassionate", "Practical", "Motivating"],
      audiences: ["Health-conscious adults", "People 40+", "Busy parents", "Beginners to fitness", "Chronic health condition managers"],
      publishingGoals: ["Amazon KDP bestseller", "Health authority platform", "Coaching funnel", "Wellness brand building"],
      subNiches: [
        sub("weight-loss", "Weight Loss",
          "Compassionate and science-backed. Moves well beyond calorie counting to address hormones, gut health, habits, and psychology of sustainable fat loss. Pacing builds from foundational nutrition science to behavioral change systems to maintenance mindset. Chapters avoid shame and focus on biological education and lifestyle design. Ideal reader outcome: sustainable weight loss with no extreme restrictions and a healthy relationship with food."),
        sub("gut-health", "Gut Health",
          "Educational and empowering. Connects microbiome science to energy, mood, immunity, and digestion in accessible, non-clinical terms. Chapters introduce progressive dietary and lifestyle shifts with practical meal guidance and supplement frameworks. Pacing moves from gut biology basics to personalized protocol design. Ideal reader outcome: a reader who understands their digestive system and has a clear dietary plan to optimize it."),
        sub("sleep-improvement", "Sleep Improvement",
          "Calming and evidence-based. Addresses the root causes of poor sleep — from circadian rhythm disruption to cortisol dysregulation — and builds a comprehensive optimization protocol. Pacing moves from sleep science fundamentals to bedroom environment design to nightly ritual construction. Chapters are written in a tone that relaxes as it educates. Ideal reader outcome: consistent deep sleep and higher daily energy."),
        sub("walking-programs", "Walking Programs",
          "Accessible and motivating. Makes movement approachable for every fitness level with structured progressive walking plans and meaningful milestones. Each chapter introduces a new walking variable — pace, terrain, duration, mindfulness — building complexity gradually. Pacing celebrates incremental wins to sustain momentum. Ideal reader outcome: a habitual daily walking practice with measurable health improvements."),
        sub("fitness-after-40", "Fitness After 40",
          "Empowering and age-positive. Addresses the unique hormonal and physical shifts of midlife with safe, science-backed training adaptations. Pacing builds from body assessment and hormonal education to progressive strength and mobility training plans. Chapters reject decline narratives and celebrate what's possible at every decade. Ideal reader outcome: a reader who feels stronger, more mobile, and more energized than they did in their 30s."),
        sub("healthy-aging", "Healthy Aging",
          "Holistic and long-term focused. Combines nutrition, movement, sleep, cognitive health, and mindset strategies for sustained vitality across the decades. Chapters blend research-backed longevity science with practical daily protocols that are simple to maintain. Pacing moves from biological aging fundamentals to a personalized longevity blueprint. Ideal reader outcome: a proactive aging strategy that optimizes health span, not just lifespan."),
        sub("stress-management", "Stress Management",
          "Calming and empowering. Equips readers with a multi-layered toolkit of proven stress reduction techniques spanning breathwork, boundary setting, cognitive reframing, and somatic practices. Pacing alternates between understanding the physiology of stress and practice-based interventions. Chapters build in complexity from quick emergency techniques to deep lifestyle restructuring. Ideal reader outcome: a personal stress management system that prevents burnout."),
        sub("hormone-balance", "Hormone Balance",
          "Educational and transformational. Demystifies hormonal health for everyday people without clinical overwhelm. Chapters cover each key hormone — cortisol, insulin, thyroid, estrogen, testosterone — its daily impact, and the dietary and lifestyle levers to restore balance. Pacing progresses from hormonal literacy to lab-informed self-advocacy to protocol design. Ideal reader outcome: a reader who understands their hormonal landscape and has a clear restoration plan."),
        sub("anti-inflammatory-living", "Anti-Inflammatory Living",
          "Preventative and practical. Guides readers through a whole-life anti-inflammatory overhaul covering food, movement, sleep, stress, and environmental toxin reduction. Pacing follows a staged transition plan — eliminate the worst offenders first, then layer in optimal choices. Chapters provide shopping lists, meal frameworks, and habit substitution strategies. Ideal reader outcome: measurable reduction in inflammation markers and a sustainable anti-inflammatory lifestyle."),
        sub("energy-optimization", "Energy Optimization",
          "Energizing and highly actionable. Identifies the major energy drains in modern life — poor sleep, blood sugar instability, sedentary behavior, chronic stress — and provides a comprehensive system for sustained, all-day vitality. Chapters build an energy-maximizing daily protocol layer by layer. Pacing uses before-and-after energy assessments at each stage. Ideal reader outcome: consistent high energy from morning to evening without stimulant dependency.")
      ]
    },
    {
      id: "computers-technology",
      label: "Computers & Technology",
      description: "Artificial intelligence, digital skills, automation, productivity technology, and modern computer literacy.",
      tones: ["Clear & demystifying", "Practical", "Forward-looking", "Accessible", "Empowering"],
      audiences: ["Non-technical professionals", "Small business owners", "Freelancers", "Career changers", "Curious lifelong learners"],
      publishingGoals: ["Amazon KDP bestseller", "Digital authority", "Course funnel", "AI consulting pipeline"],
      subNiches: [
        sub("chatgpt", "ChatGPT",
          "Practical and immediately accessible. Shows non-technical readers how to leverage ChatGPT for real, measurable productivity gains across writing, research, planning, and problem-solving. Each chapter solves a specific high-value use case with step-by-step prompt walkthroughs and copy-paste templates. Pacing moves from setup and orientation to advanced multi-step workflows. Ideal reader outcome: a daily ChatGPT user who saves hours each week."),
        sub("ai-for-beginners", "AI for Beginners",
          "Demystifying and friendly. Introduces artificial intelligence concepts in plain English, replacing fear and confusion with genuine understanding of how AI works and why it matters. Pacing moves from foundational concepts to hands-on tools to real-world personal and professional applications. Chapters avoid technical jargon and use relatable analogies throughout. Ideal reader outcome: a reader who understands AI confidently and uses it in their daily life."),
        sub("prompt-engineering", "Prompt Engineering",
          "Technical yet highly practical. Teaches the art and science of crafting AI prompts that consistently produce reliable, high-quality outputs. Chapters progress from basic prompt anatomy to advanced techniques including chain-of-thought, few-shot, and role-based prompting. Pacing follows a mastery model — concept, demonstration, practice, refinement. Ideal reader outcome: the ability to engineer prompts that get professional-grade results from any AI model."),
        sub("ai-productivity", "AI Productivity",
          "Results-oriented and systematic. Helps professionals build a personalized AI productivity stack that eliminates time-wasting tasks and amplifies output. Each chapter targets a specific workflow category — email, research, content creation, project planning — and automates it with AI toolsets. Pacing follows a productivity audit-to-implementation approach. Ideal reader outcome: a fully integrated AI productivity system saving 10+ hours per week."),
        sub("no-code-automation", "No-Code Automation",
          "Empowering and project-based. Removes the need for coding knowledge to build powerful, time-saving automations using tools like Zapier, Make, and Notion. Pacing follows a project-first approach where each chapter delivers a working, real-world automation the reader can use immediately. Chapters build in complexity from simple triggers to multi-step AI-powered workflows. Ideal reader outcome: 5+ running automations that eliminate manual, repetitive work."),
        sub("cybersecurity-basics", "Cybersecurity Basics",
          "Clear, serious, and actionable without alarmism. Makes digital safety accessible to everyday users by translating technical threats into understandable risks and simple protective actions. Chapters build a personal cybersecurity protocol from passwords and 2FA to phishing awareness to secure browsing and data backup. Pacing moves from threat awareness to full defensive setup. Ideal reader outcome: a reader whose digital life is protected by a layered, professional-grade security setup."),
        sub("digital-literacy", "Digital Literacy",
          "Patient, educational, and confidence-building. Closes the digital skills gap for readers new to or intimidated by technology. Pacing moves from device basics and internet navigation to productivity tools, online safety, and digital communication etiquette. Chapters celebrate small competency wins and build progressively. Ideal reader outcome: a confident, self-sufficient digital user who navigates the modern tech landscape with ease."),
        sub("remote-work-technology", "Remote Work Technology",
          "Practical and efficiency-focused. Covers the complete remote work tech stack — from communication and project management tools to home office hardware to async collaboration systems. Each chapter optimizes a specific area of the remote work experience with tool recommendations and setup walkthroughs. Pacing follows the remote work day from setup to shutdown. Ideal reader outcome: a remote work environment that matches or exceeds an in-office professional setup."),
        sub("ai-for-business", "AI for Business",
          "Strategic and implementation-focused. Shows business owners and managers how to integrate AI into operations, marketing, customer service, and decision-making for competitive advantage. Pacing follows a department-by-department AI adoption roadmap with ROI framing at every stage. Chapters combine strategic overview with step-by-step tool implementation. Ideal reader outcome: a business with AI embedded in its core workflows, reducing costs and increasing output."),
        sub("ai-side-hustles", "AI Side Hustles",
          "Entrepreneurial and opportunity-driven. Identifies the income opportunities created by the AI revolution and walks through launching each one from zero. Chapters combine market opportunity analysis with step-by-step business setup guides. Pacing moves from opportunity identification to first client to scalable operation. Ideal reader outcome: a running AI-powered side hustle generating its first consistent revenue within 30–60 days.")
      ]
    },
    {
      id: "psychology",
      label: "Psychology",
      description: "Human behavior, decision making, emotional processes, social influence, and cognitive understanding.",
      tones: ["Intellectual", "Analytical", "Eye-opening", "Accessible", "Practically grounded"],
      audiences: ["Curious thinkers", "Professionals in people-facing roles", "Self-improvement readers", "Students", "Leaders and managers"],
      publishingGoals: ["Amazon KDP bestseller", "Thought leadership", "Speaking platform", "Academic crossover"],
      subNiches: [
        sub("human-behavior", "Human Behavior",
          "Analytical and deeply insightful. Decodes the underlying drivers of human action — motivation, emotion, status, fear, and social pressure — using behavioral science. Chapters move from evolutionary instinct to learned patterns to social influence, building a complete picture of why people do what they do. Pacing alternates between research findings and real-world application scenarios. Ideal reader outcome: the ability to predict, understand, and empathize with human behavior in any context."),
        sub("body-language", "Body Language",
          "Observational and immediately practical. Teaches readers to read nonverbal cues with accuracy and project confidence, authority, and warmth through their own posture, gesture, and expression. Pacing alternates between decoding others' signals and self-improvement exercises with mirror and video practice. Chapters cover face, hands, posture, proximity, and voice tone systematically. Ideal reader outcome: a reader who communicates powerfully without saying a word."),
        sub("cognitive-biases", "Cognitive Biases",
          "Eye-opening and intellectually engaging. Exposes the mental shortcuts and systematic errors that distort perception, judgment, and decision-making. Each chapter names a specific bias, illustrates it with striking, relatable examples, and offers concrete debiasing strategies. Pacing builds from individual biases to their interactions in complex decisions. Ideal reader outcome: a reader who catches their own cognitive errors before they cause damage."),
        sub("persuasion", "Persuasion",
          "Strategic, nuanced, and ethically grounded. Covers the foundational principles of influence — reciprocity, social proof, authority, scarcity, liking, commitment — and shows how they operate in marketing, negotiation, leadership, and relationships. Pacing moves from psychological foundations to applied persuasion scenarios with scripts and frameworks. Ideal reader outcome: the ability to ethically influence decisions in professional and personal contexts."),
        sub("dark-psychology", "Dark Psychology",
          "Cautionary, revelatory, and empowering. Educates readers on manipulation tactics, coercive control, narcissistic abuse, and psychological exploitation so they can recognize, resist, and recover. Chapters balance awareness with ethical responsibility, covering gaslighting, love bombing, DARVO, and triangulation. Pacing progresses from pattern recognition to real-time defense to long-term boundary setting. Ideal reader outcome: immunity to psychological manipulation in all its forms."),
        sub("critical-thinking", "Critical Thinking",
          "Rigorous, empowering, and intellectually satisfying. Builds the mental tools to evaluate arguments, identify logical fallacies, assess evidence, and make better decisions under uncertainty. Pacing follows a framework-first, application-second approach with each chapter introducing a reasoning tool followed by challenging real-world exercises. Ideal reader outcome: a reader who thinks clearly, argues effectively, and is never fooled by shoddy reasoning."),
        sub("emotional-regulation", "Emotional Regulation",
          "Therapeutic in tone, practical in delivery. Helps readers understand the neuroscience of emotional response and build robust self-regulation skills for high-pressure situations. Chapters alternate between understanding the brain-body emotion system and evidence-based regulation techniques from DBT, CBT, and somatic therapy. Pacing is compassionate and gradual. Ideal reader outcome: emotional mastery — the ability to feel fully without being controlled by feelings."),
        sub("social-psychology", "Social Psychology",
          "Fascinating, accessible, and socially illuminating. Explores how groups, culture, norms, and context shape individual thought and behavior in ways people rarely notice. Pacing moves from classic conformity and obedience research to modern applications in online behavior, tribalism, and groupthink. Chapters blend research storytelling with applied social awareness strategies. Ideal reader outcome: a reader who navigates social systems with greater self-awareness and influence."),
        sub("decision-making", "Decision Making",
          "Analytical, structured, and deeply outcome-focused. Improves the quality of life, career, and financial decisions by teaching proven frameworks for evaluating options under uncertainty. Each chapter introduces a decision-making model — expected value, pre-mortem, second-order thinking, inversion — with real-life scenarios. Pacing builds a complete personal decision architecture. Ideal reader outcome: a reader who makes faster, higher-quality decisions with fewer regrets."),
        sub("manipulation-awareness", "Manipulation Awareness",
          "Protective, empowering, and clear-eyed. Exposes the common manipulation tactics used in personal relationships, workplaces, and media — from subtle guilt-tripping to systematic coercive control. Pacing progresses from recognition and pattern identification to in-the-moment boundary setting to long-term relationship auditing. Chapters are written to validate past experiences while equipping readers for future protection. Ideal reader outcome: complete awareness of when they are being manipulated and the tools to stop it immediately.")
      ]
    },
    {
      id: "teen-young-adult",
      label: "Teen & Young Adult Nonfiction",
      description: "Life skills, confidence, education, personal development, and real-world preparation for teens and young adults.",
      tones: ["Relatable", "Encouraging", "Direct", "Age-appropriate", "Empowering"],
      audiences: ["Teens aged 13–18", "Young adults 18–24", "Parents buying for teens", "School counselors", "Youth educators"],
      publishingGoals: ["Amazon KDP bestseller", "School and library market", "Gift book market", "Youth program curriculum"],
      subNiches: [
        sub("confidence-for-teens", "Confidence for Teens",
          "Encouraging and deeply relatable. Helps teenagers overcome self-doubt, social comparison, and performance anxiety through age-appropriate mindset work and real-world confidence challenges. Pacing uses short, punchy chapters with reflection prompts and scenario-based exercises drawn from actual teen experiences. Language is conversational and non-preachy. Ideal reader outcome: a teen who acts confidently in social situations, speaks up in class, and trusts their own judgment."),
        sub("study-skills", "Study Skills",
          "Practical, motivating, and immediately useful. Gives teens a complete, proven study system covering active note-taking methods, spaced repetition, test preparation, focus management, and beating procrastination. Each chapter delivers one high-impact technique the reader can apply the same day. Pacing respects the limited attention span of teen readers with concise, visual-friendly chapters. Ideal reader outcome: a 20–30% improvement in academic performance with less study time."),
        sub("social-skills", "Social Skills",
          "Warm, scenario-based, and non-judgmental. Builds real-world confidence in friendships, group dynamics, conflict navigation, and everyday communication for teens navigating complex social environments. Chapters use realistic dialogue, social scripts, and role-play frameworks. Pacing builds from listening skills to conversation to conflict resolution to leadership. Ideal reader outcome: a teen who initiates conversations easily, handles conflict maturely, and builds genuine friendships."),
        sub("time-management", "Time Management",
          "Accessible, structured, and teen-friendly. Helps young readers build time awareness, prioritize between school, activities, social life, and rest, and create personalized scheduling systems. Pacing uses visual frameworks, simple time-blocking tools, and energy-management concepts scaled to teen life. Chapters are short and use relatable scenarios. Ideal reader outcome: a teen who consistently meets deadlines, reduces last-minute stress, and has time left over for what they love."),
        sub("emotional-intelligence-teens", "Emotional Intelligence",
          "Developmentally appropriate, empathetic, and deeply validating. Helps young readers name, understand, and manage the intense emotions of adolescence with language and practical tools suited to their experience. Chapters cover self-awareness, empathy, impulse control, and social reading using relatable stories and age-appropriate frameworks. Pacing honors the emotional intensity of the teen years. Ideal reader outcome: a teen with strong emotional vocabulary, better relationships, and reduced emotional reactivity."),
        sub("career-exploration", "Career Exploration",
          "Inspiring and realistically grounded. Introduces teens to a diverse range of career paths with strengths-based self-discovery frameworks and practical exploration tools. Chapters move from values and interests assessment to industry research to informational interview and internship strategies. Pacing is forward-looking without pressure. Ideal reader outcome: a teen with clarity on 3–5 career directions that align with their authentic strengths and interests."),
        sub("goal-setting", "Goal Setting",
          "Motivating, structured, and deeply practical. Teaches teens the difference between wishes and real goals, then builds the habit systems and tracking methods to achieve them consistently. Chapters use a vision-first framework followed by actionable planning templates, habit stacking, and obstacle pre-planning. Pacing moves from inspiration to execution quickly. Ideal reader outcome: a teen with one major goal achieved and a repeatable goal-setting system for life."),
        sub("leadership-skills", "Leadership Skills",
          "Empowering, collaborative, and grounded in service. Develops leadership qualities in teens through self-awareness, effective communication, team dynamics, and ethical decision-making frameworks. Pacing moves from understanding personal leadership style to influencing peers to driving positive community impact. Chapters draw from real teen leadership scenarios in schools, sports, and community organizations. Ideal reader outcome: a teen who leads with integrity, brings out the best in others, and takes initiative."),
        sub("digital-wellness", "Digital Wellness",
          "Balanced, modern, and compassionately non-alarmist. Addresses the real pressures of social media comparison, screen addiction, cyberbullying, and digital identity with honest conversation and practical boundaries. Chapters alternate between awareness-building and healthy digital habit formation with specific, achievable phone and social media practices. Pacing respects that technology is part of teen life — the goal is balance, not abstinence. Ideal reader outcome: a teen with a healthy, intentional digital life that enhances rather than undermines their wellbeing."),
        sub("personal-finance-teens", "Personal Finance for Teens",
          "Clear, foundational, and genuinely exciting. Introduces money management, saving, budgeting, earning, and early investing in teen-friendly terms that make financial literacy feel empowering rather than boring. Pacing progresses from earning first money to smart spending to saving goals to basic investing concepts like compound interest and index funds. Chapters use real teen financial scenarios. Ideal reader outcome: a teen with an active savings habit, a budget they actually use, and their first investment account opened.")
      ]
    }
  ]
};
